adminUser:
  password: local:test/adminUser:password
  username: admin
docker:
  email: s@s.com
  password: local:test/docker:password
  url: https://192.168.20.143:5443
  username: admin
enableDocker: true
pipelineUser:
  email: ruey777@outlook.com
  token: local:test/pipelineUser:token
  username: ruey-cn
prow:
  hmacToken: local:test/prow:hmacToken
