dependencies:
- name: jxboot-resources
  repository: http://192.168.20.143:8080/jx
- alias: tekton
  name: tekton
  repository: http://192.168.20.143:8080/jx
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://192.168.20.143:8080/jx
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://192.168.20.143:8080/jx
- alias: lighthouse-jx
  condition: lighthouse.enabled
  name: lighthouse-jx
  repository: http://192.168.20.143:8080/jx
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://192.168.20.143:8080/jx
- name: jenkins-x-platform
  repository: http://192.168.20.143:8080/jx
#- condition: chartmuseum.enabled
#  name: chartmuseum
#  repository: http://192.168.20.143:8080/jx
